#!/bin/sh

# 设置主机名
# uci set system.@system[0].hostname='MyRouter'
# uci commit system

# 配置网络
# uci set network.lan.ipaddr='192.168.1.1'
# uci commit network

# 安装软件包
# opkg update
# opkg install luci

# 删除脚本自身，确保只运行一次
# rm -f /etc/uci-defaults/my-custom-config
